### ISSUE TITLE
csv/Json data not up to date

### ISSUE THREAD

**Issue by DonzCap** [pcm-dpc/UKR-2022#2]
The open data is out of date and does not match the data displayed in the report

**Comment by umbros** [comment]
updated

**Comment by DonzCap** [comment]
Hi, the json is not synced with the dashboard again. @umbros  Can you update the file?

**Comment by DonzCap** [comment]
Hi @umbros Could you please update the files ?

**Comment by DonzCap** [comment]
@umbros Are you able to automatically synchronize the dashboard data with those in the json file?
